export const routineData = [
  {
    id: 1,
    title: "turn on the light",
    time: "7:00am",
    frequent: "Every Day",
    deviceNumber: 1,
    device: [["light", true]],
    state: true,
  },
  {
    id: 2,
    title: "turn off the light",
    time: "9:00am",
    frequent: "Every Day",
    deviceNumber: 1,
    device: [["light", false]],
    state: true,
  },
  {
    id: 3,
    title: "turn on the fan",
    time: "10:00pm",
    frequent: "Every Saturday",
    deviceNumber: 1,
    device: [["fan", true]],
    state: false,
  },
  {
    id: 4,
    title: "turn off the fan",
    time: "11:00pm",
    frequent: "Every Day",
    deviceNumber: 3,
    device: [["fan", false]],
    state: false,
  },
  {
    id: 5,
    title: "open the door",
    time: "3:00am",
    frequent: "Every Friday",
    deviceNumber: 3,
    device: [["door", true]],
    state: false,
  },
  {
    id: 6,
    title: "close the door",
    time: "7:30am",
    frequent: "Every Sunday",
    deviceNumber: 3,
    device: [["door", false]],
    state: false,
  },
  {
    id: 7,
    title: "Concentrating",
    time: "1:00pm",
    frequent: "Every Day",
    deviceNumber: 3,
    device: [],
    state: false,
  },
  {
    id: 8,
    title: "Friends",
    time: "3:00pm",
    frequent: "Every Thursday",
    deviceNumber: 3,
    device: [],
    state: false,
  },
];
